frontendDockerImage: gwtm11/frontend_container:latest
frontendService:
  type: LoadBalancer
frontendDeployment:
  replicationSet:
    replicas: 1
    progressDeadlineSeconds: 120
    minReadySeconds: 30
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
serviceAccount:
  name: frontend
environment:
  orderName: ORDER_SERVICE
  orderValue: service-order
  productName: PRODUCT_SERVICE
  productValue: service-product
  userName: USER_SERVICE
  userValue: service-user
  pythonBufferName: PYTHONUNBUFFERED
  pythonBufferValue: 1

    