apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  # labels:
  #   app: webapp
  # annotations:
spec:
  replicas: 1
  progressDeadlineSeconds: 120
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gwtm11/frontend_container:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: ORDER_SERVICE
              value: "service-order"
            - name: PRODUCT_SERVICE
              value: "service-product"
            - name: USER_SERVICE
              value: "service-user"
            - name: PYTHONUNBUFFERED
              value: "1"
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "500m"
