apiVersion: v1
kind: Service
metadata:
  name: order-db
  labels:
    app: order-db
spec:
  type: ClusterIP
  selector:
    app: order-db
  ports:
    - protocol: TCP
      name: http
      port: 3306
      targetPort: 3306