apiVersion: v1
kind: Service
metadata:
  name: service-order
  labels:
    app: order
spec:
  type: ClusterIP
  selector:
    app: order
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000