apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  # labels:
  #   app: webapp
  # annotations:
spec:
  replicas: 1
  progressDeadlineSeconds: 120
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
        - name: user-db
          image: mysql:5.7.22
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "test"
          - name: MYSQL_DATABASE
            value: user
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "500m"
