apiVersion: v1
kind: Service
metadata:
  name: service-user 
  labels:
    app: user
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000