---
{{ if .Values.mysqlImage }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "dbServiceName" .}}
  labels:
    app: {{ template "labelName" .}}-db
spec:
  type: {{ .Values.dbService.type }}
  selector:
    app: {{ template "labelName" .}}-db
  ports:
    - protocol: TCP
      name: http
      port: 3306
      targetPort: 3306
  {{ end }}