apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deploy
  # labels:
  #   app: webapp
  # annotations:
spec:
  replicas: 1
  progressDeadlineSeconds: 120
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: gwtm11/product_container:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: ORDER_SERVICE
              value: "order-service"
            - name: PRODUCT_SERVICE
              value: "product-service"
            - name: USER_SERVICE
              value: "user-service"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: DB-HOST
              value: db-product
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "500m"
