apiVersion: v1
kind: Service
metadata:
  name: product-db
  labels:
    app: product-db
spec:
  type: ClusterIP
  selector:
    app: product-db
  ports:
    - protocol: TCP
      name: http
      port: 3306
      targetPort: 3306