apiVersion: v1
kind: Service
metadata:
  name: service-product 
  labels:
    app: product
spec:
  type: ClusterIP
  selector:
    app: product
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000