productDockerImage: gwtm11/product_container:latest
mysqlImage: mysql:5.7.22
productService:
  type: ClusterIP
dbService:
  type: ClusterIP
productDeployment:
  replicationSet:
    replicas: 1
    progressDeadlineSeconds: 120
    minReadySeconds: 30
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
dbDeployment:
  replicationSet:
    replicas: 1
    progressDeadlineSeconds: 120
    minReadySeconds: 30
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
serviceAccount:
  name: product
dbServiceAccount:
  name: product-db
environment:
  orderName: ORDER_SERVICE
  orderValue: service-order
  productName: PRODUCT_SERVICE
  productValue: service-product
  userName: USER_SERVICE
  userValue: service-user
  pythonBufferName: PYTHONUNBUFFERED
  pythonBufferValue: 1
  DB_NAME: MYSQL_DATABASE
  DB_VAL: product
  DB_PWD_NAME: MYSQL_ROOT_PASSWORD
  DB_PWD: test
  HOST-NAME: DB-HOST
  HOSTNAMEVALUE: db-product

    